-- ============================================================================
-- RETIRED 2026-07-29. This file is a tombstone. It contains no code.
--
-- palm6_threads was a REPLACEMENT-style clothing spike. It overwrote the base
-- game's male-torso jbib drawable 0 for every male freemode ped on the server,
-- and on 2026-07-29 it was found running on the live box while every police
-- work outfit rendered as nothing for everyone. See fxmanifest.lua for the
-- full incident write-up and docs/CUSTOM-CLOTHING.md for what to do instead.
--
-- This file is NOT declared in fxmanifest.lua and is never loaded. It is kept
-- only so the record of what the spike configured is not lost. What it used to
-- contain:
--
--     Config = {}
--     Config.Enabled = false
--     Config.Spike = { component = 11, drawable = 0, texture = 0 }
--
-- Those three numbers are the base game's OWN indices, and that was the whole
-- problem. The spike picked them precisely because they were guaranteed to
-- exist, which is another way of saying it aimed at a slot that every other
-- outfit on the server was already using. A real addon pack appends a NEW
-- drawable index instead, and nobody may author that index by hand: it has to
-- be read off the ped in game after the pack is mounted.
--
-- DO NOT restore this file to working code. DO NOT add it back to the manifest.
-- ============================================================================
