#!/usr/bin/env python3
"""
gen_pd_rooms.py — turn the headless MLO furniture extraction into pd_life's
Config.Rooms Lua block. Reads out/mrpd_interior.tsv (archetype, x, y, z, heading,
room) produced by YtypDump and selects a curated, believable set of interior NPC
posts ANCHORED TO REAL FURNITURE (resolved chairs/benches/named desks) — never a
guessed coordinate. Seated posts land a ped exactly on a chair/bench; the single
front-desk clerk is flagged (its exact stand spot gets /coords-tuned when it turns
interactive in the duty phase).

    python tools/threads-pipeline/scripts/gen_pd_rooms.py \
        tools/threads-pipeline/out/mrpd_interior.tsv

Emits Lua to stdout; paste into palm6_pd_life/shared/config.lua.
"""
import sys
from collections import defaultdict

# (model, room) -> (role, scenario, kind, cap, post_id_prefix|None)
#   role:     'cop' | 'civ'          (which model pool)
#   scenario: GTA scenario the ped runs
#   kind:     'seat'  = ped sits ON this furniture (exact, no offset)
#             'desk'  = ped stands at a desk anchor  (VERIFY/nudge in game)
#   cap:      max peds drawn from that (model,room) bucket
#   post:     if set, this is a takeable duty post (interactive phase)
SELECT = [
    # ---- seated detectives / officers at their desks (exact office-chair coords)
    ("prop_off_chair_05", "officeright",   "cop", "PROP_HUMAN_SEAT_COMPUTER", "seat", 4, None),
    ("prop_off_chair_05", "officeleft",    "cop", "PROP_HUMAN_SEAT_COMPUTER", "seat", 4, None),
    ("prop_off_chair_05", "captain",       "cop", "PROP_HUMAN_SEAT_COMPUTER", "seat", 2, "captain_desk"),
    ("prop_off_chair_05", "2ndunitoffice", "cop", "PROP_HUMAN_SEAT_COMPUTER", "seat", 3, None),
    # ---- cops taking a breather / gearing up on armory benches (exact bench coords)
    ("nteam_mrpd_bench",  "armory",        "cop", "PROP_HUMAN_SEAT_CHAIR_MP", "seat", 3, None),
    # ---- public waiting on lobby seating (exact seat coords)
    ("nteammrpdlobbyseat","mainhall",      "civ", "PROP_HUMAN_SEAT_CHAIR_MP", "seat", 5, None),
    ("nteammrpdlobbyseat","floor",         "civ", "PROP_HUMAN_SEAT_CHAIR_MP", "seat", 3, None),
    ("nteammrpdlobbyseat","2ndunithall",   "civ", "PROP_HUMAN_SEAT_CHAIR_MP", "seat", 3, None),
    ("nteammrpdlobbyseat","lefthall",      "civ", "PROP_HUMAN_SEAT_CHAIR_MP", "seat", 2, None),
    # ---- front-desk clerk: one cop at the reception desk. Its stand spot is the
    #      desk origin; gets /coords-nudged when it becomes the takeable front post.
    ("nteammainhalldesk", "mainhall",      "cop", "WORLD_HUMAN_CLIPBOARD",    "desk", 1, "front_desk"),
]


def main():
    tsv = sys.argv[1] if len(sys.argv) > 1 else "tools/threads-pipeline/out/mrpd_interior.tsv"
    # bucket rows by (model, room), preserving file order
    buckets = defaultdict(list)
    with open(tsv, encoding="utf-8") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 6:
                continue
            name, x, y, z, h, room = parts[:6]
            buckets[(name, room)].append((float(x), float(y), float(z), float(h)))

    out = []
    total = 0
    for model, room, role, scen, kind, cap, post in SELECT:
        rows = buckets.get((model, room), [])
        if not rows:
            sys.stderr.write(f"WARN no rows for {model} in {room}\n")
            continue
        for i, (x, y, z, h) in enumerate(rows[:cap]):
            pid = f"{post}" if (post and cap == 1) else (f"{post}_{i+1}" if post else None)
            postfield = f", post='{pid}'" if pid else ""
            out.append(
                f"    {{ scen='{scen}', ped='{role}', room='{room}', kind='{kind}'{postfield}, "
                f"coords=vector4({x:.2f}, {y:.2f}, {z:.2f}, {h:.1f}) }},"
            )
            total += 1

    print("-- AUTO-GENERATED by tools/threads-pipeline/scripts/gen_pd_rooms.py")
    print("-- from the NTeam MRPD interior extraction (real furniture coords, no guesses).")
    print("-- Regenerate: python tools/threads-pipeline/scripts/gen_pd_rooms.py out/mrpd_interior.tsv")
    print("Config.Rooms = {")
    print("\n".join(out))
    print("}")
    sys.stderr.write(f"emitted {total} interior posts\n")


if __name__ == "__main__":
    main()
